from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from flask import Flask, request, jsonify
from flask_cors import CORS
import os
from dotenv import load_dotenv
from google import genai


# ===============================
# LOAD ENVIRONMENT VARIABLES
# ===============================

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# ===============================
# FLASK APP
# ===============================

app = Flask(__name__)

# Allow website to communicate with Python
CORS(app)


# ===============================
# GEMINI AI CLIENT
# ===============================

client = genai.Client(
    api_key=GEMINI_API_KEY
)


# ===============================
# HOME
# ===============================

@app.route("/")
def home():

    return "AI Invoice Agent Backend is Running! 🤖"
# ===============================
# CREATE PDF INVOICE
# ===============================

def create_invoice_pdf(
    invoice_number,
    customer_name,
    customer_email,
    product_name,
    quantity,
    price,
    subtotal,
    discount,
    total,
    ai_summary
):

    filename = f"{invoice_number}.pdf"

    pdf = canvas.Canvas(filename, pagesize=A4)

    width, height = A4

    # ===============================
    # HEADER
    # ===============================

    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "AI INVOICE AGENT")

    pdf.setFont("Helvetica", 11)
    pdf.drawString(
        50,
        height - 80,
        "Muhammad Tariq Mahboob"
    )

    # ===============================
    # INVOICE INFORMATION
    # ===============================

    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(
        400,
        height - 60,
        f"Invoice: {invoice_number}"
    )

    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        400,
        height - 78,
        f"Date: {__import__('datetime').date.today()}"
    )

    # ===============================
    # BILL TO
    # ===============================

    y = height - 140

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "BILL TO")

    pdf.setFont("Helvetica", 11)
    pdf.drawString(50, y - 20, customer_name)
    pdf.drawString(50, y - 38, customer_email)

    # ===============================
    # ITEM
    # ===============================

    y = y - 90

    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(50, y, "DESCRIPTION")
    pdf.drawString(300, y, "QTY")
    pdf.drawString(360, y, "PRICE")
    pdf.drawString(460, y, "TOTAL")

    pdf.setFont("Helvetica", 10)

    pdf.drawString(50, y - 25, product_name)
    pdf.drawString(300, y - 25, str(quantity))
    pdf.drawString(360, y - 25, f"PKR {price:,.0f}")
    pdf.drawString(460, y - 25, f"PKR {subtotal:,.0f}")

    # ===============================
    # TOTALS
    # ===============================

    y = y - 90

    pdf.setFont("Helvetica", 11)
    pdf.drawString(
        350,
        y,
        f"Subtotal: PKR {subtotal:,.0f}"
    )

    pdf.drawString(
        350,
        y - 22,
        f"Discount: PKR {discount:,.0f}"
    )

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(
        350,
        y - 52,
        f"TOTAL: PKR {total:,.0f}"
    )

    # ===============================
    # AI SUMMARY
    # ===============================

    y = y - 110

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(
        50,
        y,
        "AI Invoice Summary"
    )

    pdf.setFont("Helvetica", 10)

    # Keep summary inside the PDF width
    words = ai_summary.split()
    line = ""
    line_y = y - 22

    for word in words:

        test_line = line + word + " "

        if pdf.stringWidth(test_line, "Helvetica", 10) < 480:

            line = test_line

        else:

            pdf.drawString(
                50,
                line_y,
                line
            )

            line = word + " "
            line_y -= 16

    if line:
        pdf.drawString(
            50,
            line_y,
            line
        )

    # ===============================
    # FOOTER
    # ===============================

    pdf.setFont("Helvetica", 9)

    pdf.drawString(
        50,
        40,
        "Generated by AI Invoice Agent"
    )

    pdf.drawString(
        50,
        25,
        "Muhammad Tariq Mahboob • Powered by Python + Gemini AI"
    )

    pdf.save()

    return filename


# ===============================
# CREATE INVOICE
# ===============================

@app.route("/create-invoice", methods=["POST"])
def create_invoice():

    try:

        # Get data from website
        data = request.get_json()

        customer_name = data.get("customerName", "")
        customer_email = data.get("customerEmail", "")
        product_name = data.get("productName", "")
        quantity = int(data.get("quantity", 1))
        price = float(data.get("price", 0))
        discount = float(data.get("discount", 0))


        # ===============================
        # CALCULATE INVOICE
        # ===============================

        subtotal = quantity * price

        total = max(
            subtotal - discount,
            0
        )


        # ===============================
        # GEMINI AI PROMPT
        # ===============================

        prompt = f"""
You are an AI Invoice Assistant.

Create a short, professional invoice summary.

Customer:
{customer_name}

Customer Email:
{customer_email}

Product / Service:
{product_name}

Quantity:
{quantity}

Price per Item:
PKR {price:,.0f}

Subtotal:
PKR {subtotal:,.0f}

Discount:
PKR {discount:,.0f}

Total:
PKR {total:,.0f}

Write a professional 2-3 sentence summary for the invoice.
Do not invent any information.
"""


        # ===============================
        # SEND TO GEMINI
        # ===============================

        response = client.models.generate_content(
            model="gemini-3.6-flash",
            contents=prompt
        )


        ai_summary = response.text
        
        # ===============================
        # GENERATE PDF
        # ===============================

        invoice_number = "INV-" + str(__import__("time").time()).replace(".", "")[-8:]

        pdf_file = create_invoice_pdf(
            invoice_number,
            customer_name,
            customer_email,
            product_name,
            quantity,
            price,
            subtotal,
            discount,
            total,
            ai_summary
        )

        # ===============================
        # RETURN RESULT
        # ===============================

        return jsonify({

            "success": True,

            "message": "Invoice created successfully with Gemini AI! 🤖",

            "invoice": {

                "customerName": customer_name,
                "customerEmail": customer_email,
                "productName": product_name,
                "quantity": quantity,
                "price": price,
                "subtotal": subtotal,
                "discount": discount,
                                "total": total,

                "aiSummary": ai_summary,

                "invoiceNumber": invoice_number,
                "pdfFile": pdf_file
            }

        })


    except Exception as error:

        print("ERROR:", error)

        return jsonify({

            "success": False,

            "message": "Something went wrong while creating the invoice.",

            "error": str(error)

        }), 500



# ===============================
# DOWNLOAD GENERATED PDF
# ===============================

@app.route("/download-pdf/<filename>", methods=["GET"])
def download_pdf(filename):
    from flask import send_file

    file_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        filename
    )

    if os.path.exists(file_path):
        return send_file(
            file_path,
            as_attachment=True,
            download_name=filename,
            mimetype="application/pdf"
        )

    return jsonify({
        "success": False,
        "message": "PDF file not found."
    }), 404

if __name__ == "__main__":

    app.run(
        host="127.0.0.1",
        port=5000,
        debug=True
    )